import { XAccount, Project } from './types';

export const MOCK_ACCOUNTS: XAccount[] = [
  {
    id: '1',
    handle: '@filmfare',
    displayName: 'Filmfare',
    followers: 6329093,
    category: 'TECH',
    addedDate: '2026-04-01',
    avatarUrl: 'https://picsum.photos/seed/filmfare/100/100',
    badge: 'GOLD',
  },
  {
    id: '2',
    handle: '@CNNChile',
    displayName: 'CNN Chile',
    followers: 4076952,
    category: 'NEWS',
    addedDate: '2026-04-10',
    avatarUrl: 'https://picsum.photos/seed/cnn/100/100',
    badge: 'BLUE',
  },
  {
    id: '3',
    handle: '@NASA_Community',
    displayName: 'NASA Community',
    followers: 2618347,
    category: 'TECH',
    addedDate: '2026-04-01',
    avatarUrl: 'https://picsum.photos/seed/nasa/100/100',
  },
  {
    id: '4',
    handle: '@ZambelliRita_',
    displayName: 'Carla Zambelli',
    followers: 2617605,
    category: 'POLITICS',
    addedDate: '2026-03-12',
    avatarUrl: 'https://picsum.photos/seed/carla/100/100',
  },
  {
    id: '5',
    handle: '@yogishiramdev',
    displayName: 'स्वामी रामदेव',
    followers: 2461926,
    category: 'INFLUENCER',
    addedDate: '2026-03-17',
    avatarUrl: 'https://picsum.photos/seed/yogi/100/100',
    badge: 'BLUE',
  },
  {
    id: '6',
    handle: '@FortuneMagazine',
    displayName: 'FORTUNE',
    followers: 2250399,
    category: 'NEWS',
    addedDate: '2026-03-12',
    avatarUrl: 'https://picsum.photos/seed/fortune/100/100',
    badge: 'GOLD',
  },
  {
    id: '7',
    handle: '@DCI_Kenya',
    displayName: 'DCI KENYA',
    followers: 1970974,
    category: 'GOV',
    addedDate: '2026-03-12',
    avatarUrl: 'https://picsum.photos/seed/dci/100/100',
    badge: 'BLUE',
  },
  {
    id: '8',
    handle: '@marcelamcgowan',
    displayName: 'Macela Mc Gowan',
    followers: 989617,
    category: 'INFLUENCER',
    addedDate: '2026-03-17',
    avatarUrl: 'https://picsum.photos/seed/macela/100/100',
    badge: 'BLUE',
  }
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: 'Tech Influencers 2026',
    description: 'Main project for tracking top tech accounts in the EMEA region.',
    accountCount: 124,
    status: 'ACTIVE',
    lastModified: '2026-04-15',
  },
  {
    id: '2',
    name: 'News Aggregators',
    description: 'Global news outlets and independent journalists.',
    accountCount: 45,
    status: 'ACTIVE',
    lastModified: '2026-04-12',
  },
  {
    id: '3',
    name: 'Politics Archive',
    description: 'Historical data for political discourse tracking.',
    accountCount: 89,
    status: 'ARCHIVED',
    lastModified: '2026-03-01',
  },
  {
    id: '4',
    name: 'Entertainment Hub',
    description: 'Movie stars, musicians, and pop culture icons.',
    accountCount: 210,
    status: 'ACTIVE',
    lastModified: '2026-04-16',
  }
];
